# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-transcript-verify',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-transcript-verify',
                'lib_path': 'cjm_transcript_verify'},
  'syms': {}}
