"""HTML ID constants for Phase 4: Verify"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['VerifyHtmlIds']

# %% ../nbs/html_ids.ipynb #verify-html-ids-class
# Framework-agnostic — no external imports needed

class VerifyHtmlIds:
    """HTML ID constants for Phase 4: Verify."""

    @staticmethod
    def as_selector(
        id_str: str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Main Layout
    VERIFY_CONTAINER = "sd-verify-container"
    VERIFY_CONTENT = "sd-verify-content"
    
    # Summary Sections
    DOCUMENT_SECTION = "sd-verify-document"
    SEGMENTS_SECTION = "sd-verify-segments"
    INTEGRITY_SECTION = "sd-verify-integrity"
    SOURCES_SECTION = "sd-verify-sources"
    
    # Sample Segments
    SAMPLES_SECTION = "sd-verify-samples"
    FIRST_SAMPLES = "sd-verify-first-samples"
    LAST_SAMPLES = "sd-verify-last-samples"
    JUMP_SAMPLE = "sd-verify-jump-sample"
    
    # Jump-to-index
    JUMP_INPUT = "sd-verify-jump-input"
    JUMP_BUTTON = "sd-verify-jump-button"
    JUMP_RESULT = "sd-verify-jump-result"
    JUMP_ERROR = "sd-verify-jump-error"
    JUMP_LOADING = "sd-verify-jump-loading"
    
    # Footer & Toolbar
    VERIFY_TOOLBAR = "sd-verify-toolbar"
    VERIFY_FOOTER = "sd-verify-footer"
    
    # Keyboard
    KEYBOARD_HINTS = "sd-verify-keyboard-hints"
